// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbz3pxyfJhS0ZYw7iyMJDwjQtsYhWeqwE',
    appId: '1:842006569127:web:3bba87989009193c853b82',
    messagingSenderId: '842006569127',
    projectId: 'travexel-4b250',
    authDomain: 'travexel-4b250.firebaseapp.com',
    storageBucket: 'travexel-4b250.firebasestorage.app',
    measurementId: 'G-74NWFN4YZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6bjOy6Gibhf9BwDMdYT1d9oiIa44ykuc',
    appId: '1:842006569127:android:fdfcdfb9253c51dd853b82',
    messagingSenderId: '842006569127',
    projectId: 'travexel-4b250',
    storageBucket: 'travexel-4b250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfMyLqr44g4UIP2TBkq1WdJ6bMCxb2RI',
    appId: '1:842006569127:ios:e5cbed300dc636ea853b82',
    messagingSenderId: '842006569127',
    projectId: 'travexel-4b250',
    storageBucket: 'travexel-4b250.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDfMyLqr44g4UIP2TBkq1WdJ6bMCxb2RI',
    appId: '1:842006569127:ios:e5cbed300dc636ea853b82',
    messagingSenderId: '842006569127',
    projectId: 'travexel-4b250',
    storageBucket: 'travexel-4b250.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbz3pxyfJhS0ZYw7iyMJDwjQtsYhWeqwE',
    appId: '1:842006569127:web:82ba3619fc02c2a1853b82',
    messagingSenderId: '842006569127',
    projectId: 'travexel-4b250',
    authDomain: 'travexel-4b250.firebaseapp.com',
    storageBucket: 'travexel-4b250.firebasestorage.app',
    measurementId: 'G-46XGVL5JTC',
  );
}
